version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    #build:
      #context: ./keycloak
    ports:
      - 8080:8080
    networks:
      - demonet
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - "./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro"
    command: ["start-dev", "--import-realm"]

  envoy:
    build:
      context: ./envoy
    ports:
      - 10000:10000
    networks:
      - demonet

  upstream:
    image: nginx
    networks:
      - demonet

networks:
  demonet: {}
