version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    #build:
    #context: ./keycloak
    ports:
      - 8080:8080
    networks:
      - demonet
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - "./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro"
    command: [ "start-dev", "--import-realm" ]

  envoy:
    build:
      context: ./envoy
    ports:
      - 10000:10000
    networks:
      - demonet

  oidcapp:
    image: beryju/oidc-test-client
    ports:
      - 9009:9009
    environment:
      OIDC_CLIENT_ID: oidc-tester
      OIDC_CLIENT_SECRET: 3nhYktR0LLTiPRD7Mit6331cC0h9DKgu
      OIDC_PROVIDER: http://keycloak:8080/realms/demorealm
    networks:
      - demonet
    depends_on:
      - keycloak

  simpleapp:
    image: nginx
    ports:
      - 9008:80
    networks:
      - demonet

networks:
  demonet: {}
